development:
  adapter: postgresql
  database: mydb
  pool: 5
  encoding: utf8
  username: admin
  password: admin
  host:  localhost
test:
  adapter: postgresql
  database: mydb
  pool: 5
  encoding: utf8
  username: admin
  password: admin
  host:  localhost
production:
  adapter: postgresql
  database: mydb
  pool: 5
  encoding: utf8
  username: admin
  password: admin
  host:  localhost
